name: poc

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake>=4.0.2,<5
  - cpputest>=4.0,<5
  - spdlog>=1.15.3,<2
  - cppcheck>=2.17.1,<3
  - make>=4.4.1,<5
  - doxygen>=1.13.2,<2
  - plantuml>=1.2025.3,<2
  - python>=3.13.1,<3.14
  - pip>=25.1.1,<26
  - graphviz>=12.2.1,<13
  - go-shfmt>=3.11.0,<4
  - shellcheck>=0.10.0,<1
  # clang-tidy is part of clang-tools, however it still needs clang & clangxx
  # in order to work properly.
  - clang>=20.1.6,<21
  - clangxx>=20.1.6,<21
  - clang-tools>=20.1.6,<21
  - include-what-you-use>=0.24,<1
  - pybind11>=2.13.6,<3
  # tox will be used for the automated integration tests of this library.
  - tox>=4.27.0,<5
  - cpp-argparse>=3.2,<4
  - pip:
    - -r requirements.txt
